# Generated by Django 4.2.11 on 2024-03-10 08:02

import cruds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, validators=[cruds.models.validate_title], verbose_name='title')),
            ],
        ),
    ]
